"""Initial migration

Revision ID: 1ebc440417e6
Revises: 
Create Date: 2026-03-22 22:35:21.219345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebc440417e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('real_name', sa.String(length=50), nullable=False, comment='真实姓名'),
    sa.Column('student_id', sa.String(length=20), nullable=False, comment='学号'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_student_id'), ['student_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_username'), ['username'], unique=True)

    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False, comment='教师ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('real_name', sa.String(length=50), nullable=False, comment='真实姓名'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_teachers_username'), ['username'], unique=True)

    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False, comment='班级ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='班级名称'),
    sa.Column('class_code', sa.String(length=20), nullable=False, comment='班级邀请码'),
    sa.Column('description', sa.Text(), nullable=True, comment='班级描述'),
    sa.Column('teacher_id', sa.Integer(), nullable=False, comment='教师ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_class_code'), ['class_code'], unique=True)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False, comment='测试ID'),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='班级ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='测试标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='测试描述'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='持续时间(分钟)'),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=True, comment='最大尝试次数'),
    sa.Column('show_correct_after_submit', sa.Boolean(), nullable=True, comment='提交后是否显示正确答案'),
    sa.Column('is_published', sa.Boolean(), nullable=True, comment='是否已发布'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False, comment='签到ID'),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='班级ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=6), nullable=True, comment='纬度'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=6), nullable=True, comment='经度'),
    sa.Column('location_hash', sa.String(length=100), nullable=True, comment='位置哈希'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='签到时间'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态: 1-正常, 0-无效'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_students',
    sa.Column('id', sa.Integer(), nullable=False, comment='关联ID'),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='班级ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('joined_at', sa.DateTime(), nullable=True, comment='加入时间'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态: 1-正常, 0-已退出'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('assessment_id', sa.Integer(), nullable=False, comment='测试ID'),
    sa.Column('question_type', sa.SmallInteger(), nullable=True, comment='题型: 1-单选, 2-多选'),
    sa.Column('content', sa.Text(), nullable=False, comment='题目内容'),
    sa.Column('option_a', sa.String(length=500), nullable=False, comment='选项A'),
    sa.Column('option_b', sa.String(length=500), nullable=False, comment='选项B'),
    sa.Column('option_c', sa.String(length=500), nullable=True, comment='选项C'),
    sa.Column('option_d', sa.String(length=500), nullable=True, comment='选项D'),
    sa.Column('correct_answer', sa.String(length=50), nullable=False, comment='正确答案'),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='分值'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False, comment='答案ID'),
    sa.Column('assessment_id', sa.Integer(), nullable=False, comment='测试ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='学生ID'),
    sa.Column('selected_option', sa.String(length=50), nullable=False, comment='选择的答案'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='是否正确'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True, comment='答题耗时(秒)'),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=True, comment='尝试次数'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('class_students')
    op.drop_table('checkins')
    op.drop_table('assessments')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_class_code'))

    op.drop_table('classes')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_username'))
        batch_op.drop_index(batch_op.f('ix_teachers_email'))

    op.drop_table('teachers')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_username'))
        batch_op.drop_index(batch_op.f('ix_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_students_email'))

    op.drop_table('students')
    # ### end Alembic commands ###
